# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('CUR_IdCurso', models.AutoField(primary_key=True, serialize=False)),
                ('CUR_DssCurso', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CursosDisciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDS_IdCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cursos')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasEmentas',
            fields=[
                ('DIS_IdDisciplina', models.AutoField(primary_key=True, serialize=False)),
                ('DIS_DssDisciplina', models.CharField(default='', max_length=40)),
                ('DIS_DssEmenta', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('PRF_IdPerfil', models.AutoField(primary_key=True, serialize=False)),
                ('PRF_DssPerfil', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlanosEnsinos',
            fields=[
                ('PLE_IdPlanoEnsino', models.AutoField(primary_key=True, serialize=False)),
                ('PLE_DssPlanoEnsino', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('USR_IdRA', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('USR_DssNome', models.CharField(default='', max_length=70)),
                ('USR_DssSenha', models.CharField(default='', max_length=12)),
                ('USR_IdPerfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Perfis')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinasPlanosEnsinos',
            fields=[
                ('DPL_IdDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.DisciplinasEmentas')),
                ('DPL_IdPlanoEnsino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlanosEnsinos')),
            ],
        ),
        migrations.AddField(
            model_name='cursosdisciplinas',
            name='CDS_IdDisciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinasEmentas'),
        ),
    ]
